import "styles/globals.css";
import "styles/nprogress.css";

import css from "./index.module.css";

export const metadata = {
	title: "EventLoop?",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body>
				<section className={css.layout}>
					{children}
				</section>
			</body>
		</html>
	);
}
