
export default function Layout({ children }: { children: React.ReactNode }) {
	return (
		<>
			{children}
		</>
	);
}

export const metadata = {
	title: "EventLoop?",
	description: "Generated by create next app",
};
